### ISSUE TITLE
Retrieving data from join table

### ISSUE THREAD

**Issue by MBKeeler** [MBKeeler/BNBSL-Batting-Order-Front-End#2]
Worked this issue most of the day. Two resources (players & seasons) with a join table of playerseasons. I am trying to retrieve all players associated with a season by querying the player seasons table. Unsure which route to use to get this information since a seasonplayer is not really browsable (has no useful data for user). I suspect we need to put custom code in the season_controller, but not sure.

Will be in Friday morning. Controller code below;

Example PlayerSeasons Controler

class PlayerSeasonsController < ApplicationController
# class PlayerSeasonsController < ProtectedController
  before_action :set_player_season, only: [:show, :update, :destroy]

  # GET /player_seasons
  def index
    @player_seasons = PlayerSeason.all
    # binding.pry
    render json: @player_seasons

  end

  # GET /player_seasons/1
  def show
    @player_season.player = Player.find(@player_season)
    @player_season.season = Season.find(@player_season.season_id)
binding.pry
    render json: @player_season
  end

  # POST /player_seasons
  def create
    @player_season = PlayerSeason.new(player_season_params)
    # @player_season = current_user.player_seasons.build(player_season_params)

    if @player_season.save
      render json: @player_season, status: :created
    else
      render json: @player_season.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /player_seasons/1
  def update
    if @player_season.update(player_season_params)
      render json: @player_season
    else
      render json: @player_season.errors, status: :unprocessable_entity
    end
  end

  # DELETE /player_seasons/1
  def destroy
    @player_season.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_season
      @player_season = PlayerSeason.find(params[:id])
      # @player_season = current_user.player_seasons.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def player_season_params
      params.require(:player_season).permit(:season_id, :player_id)
    end
end
```rb

SeasonController
```rb
# frozen_string_literal: true

class SeasonsController < ProtectedController
# class SeasonsController < ApplicationController
  before_action :set_season, only: [:update, :destroy]

  # GET /players
  def index
    @seasons = Season.all
    render json: @seasons
  end

  # GET /seasons/1
  def show
    render json: Season.find_by(year: params[:season][:year], program: params[:season][:program])
  end

  # POST /players
  def create
    @season = current_user.seasons.build(season_params)

    if @season.save
      render json: @season, status: :created, location: @season
    else
      render json: @season.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /seasons/1
  def update
    if @season.update(season_params)
      render json: @season
    else
      render json: @season.errors, status: :unprocessable_entity
    end
  end

  # DELETE /seasons/1
  def destroy
    # added current_user line below
    if @season.destroy
      render json: @season
    else
      render json: @season.errors, status: :unprocessable_entity
    end
  end

  private

      # Use callbacks to share common setup or constraints between actions.
      def set_season
        # @season = Season.find(params[:id])
        @season = current_user.seasons.find(params[:id])
      end
      # Only allow a trusted parameter "white list" through.
      def season_params
        params.require(:season).permit(:year, :team, :program)
      end
end
#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_season
#       @player = Player.find(params[:id])
#     end
#
#     # Only allow a trusted parameter "white list" through.
#     def player_params
#       params.fetch(:player, {})
#     end
# end

```rb

Player Controller
```rb
# frozen_string_literal: true

class PlayersController < ProtectedController
# class PlayersController < ApplicationController
  before_action :set_player, only: [:update, :destroy]

  # GET /players
  def index
    @players = Player.all
    render json: @players
  end

  # GET /players/1
  def show
    # binding.pry
    render json: Player.find_by(team: params[:player][:team])
    # render json: Player.find_by(team: params[:player][:team], year: params[:season][:year])
  end

  # POST /players
  def create
    @player = current_user.players.build(player_params)

    if @player.save
      render json: @player, status: :created, location: @player
    else
      render json: @player.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /players/1
  def update
    if @player.update(player_params)
      render json: @player
    else
      render json: @player.errors, status: :unprocessable_entity
    end
  end

  # DELETE /players/1
  def destroy
    # added current_user line below
    if @player.destroy
      render json: @player
    else
      render json: @player.errors, status: :unprocessable_entity
    end
  end

  private
      # Use callbacks to share common setup or constraints between actions.
      def set_player
        # @player = Player.find(params[:id])
        @player = current_user.players.find(params[:id])
      end
      # Only allow a trusted parameter "white list" through.
      def player_params
        # params.require(:player).permit(:first_name, :last_name, :position, :team, :program, :notes, :batting_avg, :batting_position)
          params.require(:player).permit(:first_name, :last_name, :position, :team, :program, :notes, :batting_avg, :batting_position)
      end
end
```rb

**Comment by MBKeeler** [comment]
Per response from canpan14  today:

"No reason to query the join table like that. Instead query the season table and set up a has_many players through playerseasons (or whatever you called the table) relationship.
Then when you do a get on a season, it will return all the player objects associated with the season."

**Comment by MBKeeler** [comment]
When I render the json I now see all seasons with an array of players.  I need to filter just on the parameters that I passed. I have not been able to successfully do this yet (more than 1/2 hour spent)

```
  # GET /seasons/1
  def show
    render json: Season.find_by(year: params[:season][:year], program: params[:season][:program])
  end
```

resulting json
```
{"seasons":[{"id":1,"year":"2018","team":"Dodgers","program":"AAA","players":[{"id":7,"first_name":"Mary","last_name":"Kessle","team":"Astros","program":"Triple A","notes":"notes","position":"4 - 2nd Base","batting_avg":123,"created_at":"2017-12-02T20:12:32.358Z","updated_at":"2017-12-02T20:12:32.358Z","user_id":1,"batting_position":"5"},{"id":8,"first_name":"Mary","last_name":"Kessle","team":"Astros","program":"Triple A","notes":"notes","position":"4 - 2nd Base","batting_avg":123,"created_at":"2017-12-02T20:42:48.863Z","updated_at":"2017-12-02T20:42:48.863Z","user_id":1,"batting_position":"5"}]},{"id":3,"year":"2018","team":"Astros","program":"Majors","players":[{"id":3,"first_name":"Gino","last_name":"Spinelli","team":"Astros","program":"AAA","notes":"notes","position":"Short","batting_avg":295,"created_at":"2017-11-28T14:17:09.522Z","updated_at":"2017-11-28T17:08:44.599Z","user_id":1,"batting_position":"4"}]},{"id":4,"year":"2019","team":"Astros","program":"Single A","players":[]},{"id":5,"year":"2020","team":"Astros","program":"Double A","players":[]},{"id":6,"year":"2021","team":"B/N Flames","program":"Softball Seniors","players":[]}]}~/wdi/capstone-project/BNBSL-Batting/back-end/BNBSL-batting-roster-back (return-data-work)
```

**Comment by MBKeeler** [comment]
In running the curl script for index (on seasons) I get the same basic json response as show.

**Comment by BenGitsCode** [comment]
Have you tried filtering that response with your serializer?

**Comment by MBKeeler** [comment]
will try.  working on cleaning up front end

**Comment by MBKeeler** [comment]
Fixed.  After talking with Dan on Friday I was able to figure out how to put get my Show method for season back to it's original state (which I had changed early on). Simplifying the show method gives me back just the data I needed.
